### PR TITLE
Rebase sg2042-master on release v6.8

### PR DESCRIPTION
**Pull request by silvanshade**
This PR just rebases the `sg2042-master` branch on to `v6.8` release upstream.

### CODE REVIEW

**Comment by xingxg2022** [comment]
"This branch cannot be rebased due to too many changes"

I will rebase it

**Comment by kth5** [comment]
I does work, mostly anyway. Compiles cleanly with my .config but fails to bring up any but - seemingly - the first CPU core on a Milk-V Pioneer. The rest of the cores are detected but stay marked offline.

**Comment by skeuchel** [comment]
> I does work, mostly anyway. Compiles cleanly with my .config but fails to bring up any but - seemingly - the first CPU core on a Milk-V Pioneer. The rest of the cores are detected but stay marked offline.

I have the same issue with 128G of ram, it brings up all cores with 64G though. I am currently doing that since I find this branch still more stable than the `sg2042-dev` branch.

**Comment by kth5** [comment]
@skeuchel `sg2042-dev` is unstable indeed. Brings up my box just fine but when under load (compiling a kernel with `make -j48` for instance), GCC is randomly segfaulting. I haven't given this one an indepth try yet to see about general stability since a single core is fairly useless to me.

Generally speaking, I would love to see the upgrade to 6.8.x to get the Intel Xe driver without massively patching my kernel sources to get i915 going with my ARC380 instead.

**Comment by silvanshade** [comment]
> > I does work, mostly anyway. Compiles cleanly with my .config but fails to bring up any but - seemingly - the first CPU core on a Milk-V Pioneer. The rest of the cores are detected but stay marked offline.
> 
> I have the same issue with 128G of ram, it brings up all cores with 64G though. I am currently doing that since I find this branch still more stable than the `sg2042-dev` branch.

@kth5 @skeuchel Can either of you check, when you encounter this issue when booting with 128GB of RAM, whether you can re-enable the offline harts?

You should be able to re-enable the offline harts through CPU hotplug interface:

```bash
for i in {0..63}; do echo 1 > /sys/devices/system/cpu/cpu$i/online; done
```

I haven't had a chance to test this yet running a proper installation but it at least seems to work in the linuxboot u-root shell (on 6.8 kernel with 128GB RAM on a Pioneer V1.2 board). Before running the above command, only 1 hart shows up in `/cpu/procinfo`, but after running it, all 64 are listed.

**Comment by kth5** [comment]
@silvanshade I'll have another go at it this evening (`CET`).

I am running a V1.3 afaik and yes, with the full compliment of 128GB RAM.

Also, all cores were listed but marked `offline` much like hotplugging on `ppc64le` when disabling cores on run-time.

Will report back once I've tried enabling them manually after boot.

**Comment by silvanshade** [comment]
Thanks.

One thing to note is that I am using the kernel from the branch [here](https://github.com/milkv-community/linux/tree/v6.8-sg2042-milkv-community), which is based on this PR.

The current `sg2042-master` has been updated with a different non-overlapping set of commits including a number of changes to the device tree and I haven't experimented with that yet.

**Comment by kth5** [comment]
I'll head over to the `milkv-community` repo and file the issue there if it doesn't yet exist. Queued a build just now.

**Pull request closed without merging**
