### PR TITLE
Support DCN-enabled AMD Graphics cards

### PR DESCRIPTION
**Pull request by Icenowy**

### CODE REVIEW

**Comment by Icenowy** [comment]
force pushed to add my own SoB.

**Comment by Icenowy** [comment]
Have run SuperTuxKart on Pioneer + RX7600 ( `0000:03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 33 [Radeon RX 7700S/7600S] [1002:7480] (rev cf)` ) for ~20h.

**Comment by silvanshade** [comment]
@Icenowy Do you know if this still works on `sg2042-master` branch (as of https://github.com/sophgo/linux-riscv/commit/257e38596db40eef4a23412d91d57e888f20d581)?

If it does still work for you, can you share your kernel config or any other details about your system configuration?

I am trying to get an RX 7800 XT to work with a Pioneer 1.2 board but getting a kernel oops as soon as it finishes loading all the firmwares, after the message `[drm] Display Core failed to initialize`.

**Comment by Icenowy** [comment]
@silvanshade 
1. I don't have spare Pioneer to test now.
2. I do not support the 6.6 kernel.

**Comment by xingxg2022** [comment]
you may try revert "e7d0ed665196 drivers: pci: support msix in PCIe rc0 for milkv mainboard"
________________________________
发件人: silvanshade ***@***.***>
发送时间: 2024年3月26日 19:52
收件人: sophgo/linux-riscv ***@***.***>
抄送: xiaoguang.xing 邢晓光 ***@***.***>; State change ***@***.***>
主题: Re: [sophgo/linux-riscv] Support DCN-enabled AMD Graphics cards (PR #100)


@Icenowy<https://github.com/Icenowy> Do you know if this still works on sg2042-master branch (as of 257e385<https://github.com/sophgo/linux-riscv/commit/257e38596db40eef4a23412d91d57e888f20d581>)?

If it does still work for you, can you share your kernel config or any other details about your system configuration?

I am trying to get an RX 7800 XT to work with a Pioneer 1.2 board but getting a kernel oops as soon as it finishes loading all the firmwares, after the message [drm] Display Core failed to initialize.

―

**Pull request merged**
